# fly.toml app configuration file generated for genar-ssh-portfolio on 2025-11-20T22:31:48+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'genar-ssh-portfolio'
primary_region = 'cdg'

[build]

[env]
  PORT = '23234'

[http_service]
  internal_port = 23234
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 80

[[services]]
  protocol = 'tcp'
  internal_port = 23234

  [[services.ports]]
    port = 22

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'

[[vm]]
  size = 'shared-cpu-1x'
